version: "3.3"
services:
  frontend:
    image: alimizan/frontend:v1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    deploy:
      replicas: 2
    container_name: frontend
    build: front-end-S-ONE/
    #environment:
    #- DATABASE_URI=${DATABASE_URI}
    #- SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
    #- SECRET_KEY=${SECRET_KEY}

  insultservicetwo:
    image: alimizan/insultservicetwo:${SERVICE_VERSION}
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
    deploy:
      replicas: 2
    container_name: insultservicetwo
    build: insult-sentance-generator-S-TWO/

  insultservicethree:
    image: alimizan/insultservicethree:${SERVICE_VERSION}
    ports:
    - target: 5002
      published: 5002
      protocol: tcp
    deploy:
      replicas: 2
    container_name: insultservicethree
    build: insult-word-generator-S-THREE/

  insultjoinerservicefour:
    image: alimizan/insultjoinerservicefour:${SERVICE_VERSION}
    ports:
    - target: 5003
      published: 5003
      protocol: tcp
    deploy:
      replicas: 3
    container_name: insultjoinerservicefour
    build: insultjoiner-S-FOUR/

  insultjoinerservicefive:
    image: alimizan/insultjoinerservicefive:v1
    ports:
    - target: 5004
      published: 5004
      protocol: tcp
    deploy:
      replicas: 2
    container_name: insultjoinerservicefive
    build: meme-generator-S-FIVE/
