version: "3.7"
services:
  frontend:
    image: alimizan/frontend
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    deploy:
      replicas: 2
    container_name: frontend
    build: front-end-S-ONE/
    environment:
    - USERNAME=${USERNAME}
    - PASSWORD=${PASSWORD}
    - MYSQL_URL=${MYSQL_URL}
    - MYSQL_DB=${MYSQL_DB}
    - SECRET_KEY=${SECRET_KEY}

  insultservicetwo:
    image: alimizan/insultservicetwo:${SERVICE_VERSION}
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
    deploy:
      replicas: 2
    container_name: insultservicetwo
    build: insult-sentance-generator-S-TWO/

  insultservicethree:
    image: alimizan/insultservicethree:${SERVICE_VERSION}
    ports:
    - target: 5002
      published: 5002
      protocol: tcp
    deploy:
      replicas: 2
    container_name: insultservicethree
    build: insult-word-generator-S-THREE/

  insultjoinerservicefour:
    image: alimizan/insultjoinerservicefour:${SERVICE_VERSION}
    ports:
    - target: 5003
      published: 5003
      protocol: tcp
    deploy:
      replicas: 3
    container_name: insultjoinerservicefour
    build: insultjoiner-S-FOUR/

  insultjoinerservicefive:
    image: alimizan/insultjoinerservicefive
    ports:
    - target: 5004
      published: 5004
      protocol: tcp
    deploy:
      replicas: 2
    container_name: insultjoinerservicefive
    build: meme-generator-S-FIVE/
