version: "3.7"
services:
  frontend:
    image: alimizan/frontend
    deploy:
      replicas: 2
    container_name: frontend
    build: front-end-S-ONE/
    environment:
    - USERNAME=${USERNAME}
    - PASSWORD=${PASSWORD}
    - MYSQL_URL=${MYSQL_URL}
    - MYSQL_DB=${MYSQL_DB}
    - SECRET_KEY=${SECRET_KEY}

  insult-service-two:
    image: alimizan/insultservicetwo
    deploy:
      replicas: 2
    container_name: insultservicetwo
    build: insult-sentance-generator-S-TWO/

  insult-service-three:
    image: alimizan/insultservicethree
    deploy:
      replicas: 2
    container_name: insultservicethree
    build: insult-word-generator-S-THREE/

  insult-service-four:
    image: alimizan/insultjoinerservicefour
    deploy:
      replicas: 3
    container_name: insultjoinerservicefour
    build: insultjoiner-S-FOUR/

  insult-service-five:
    image: alimizan/insultjoinerservicefive
    deploy:
      replicas: 2
    container_name: insultjoinerservicefive
    build: meme-generator-S-FIVE/

  nginx:
    image: nginx:latest
    deploy:
      replicas: 2
    container_name: nginx
    ports:
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
      - frontend
