- hosts: swarm
  become: true
  vars:
    service: docker
  tasks:
  - name: Install "{{ service }}"
    apt:
      name: "{{ service }}"
      state: latest
      update_cache: true
  - name: Start "{{ service }}" Service
    service:
      name: "{{ service }}"
      state: started

