apiVersion: v1
kind: Service
metadata:
  name: insultservicethree
spec:
  selector:
    app: insultservicethree
  ports: 
  - protocol: TCP
    port: 5002
    targetPort: 5002
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insultservicethree
  labels:
    app: insultservicethree
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insultservicethree
  template:
    metadata:
      labels:
        app: insultservicethree
    spec:
      containers:
      - name: insultservicethree
        image: alimizan/insultservicethree:v1
        ports:
        - containerPort: 5002
