apiVersion: v1
kind: Service
metadata:
  name: insultservicetwo
spec:
  selector:
    app: insultservicetwo
  ports: 
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insultservicetwo
  labels:
    app: insultservicetwo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insultservicetwo
  template:
    metadata:
      labels:
        app: insultservicetwo
    spec:
      containers:
      - name: insultservicetwo
        image: alimizan/insultservicetwo:v1
        ports:
        - containerPort: 5001
