apiVersion: v1
kind: Service
metadata:
  name: insultjoinerservicefour
spec:
  selector:
    app: insultjoinerservicefour
  ports: 
  - protocol: TCP
    port: 5003
    targetPort: 5003
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insultjoinerservicefour
  labels:
    app: insultjoinerservicefour
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insultjoinerservicefour
  template:
    metadata:
      labels:
        app: insultjoinerservicefour
    spec:
      containers:
      - name: insultjoinerservicefour
        image: alimizan/insultjoinerservicefour:v1
        ports:
        - containerPort: 5003
