apiVersion: v1
kind: Service
metadata:
  name: insultjoinerservicefive
spec:
  selector:
    app: insultjoinerservicefive
  ports: 
  - protocol: TCP
    port: 5004
    targetPort: 5004
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insultjoinerservicefive
  labels:
    app: insultjoinerservicefive
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insultjoinerservicefive
  template:
    metadata:
      labels:
        app: insultjoinerservicefive
    spec:
      containers:
      - name: insultjoinerservicefive
        image: alimizan/insultjoinerservicefive:v1
        ports:
        - containerPort: 5004
